# Generated by Django 5.2.8 on 2025-12-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_line', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('strength', models.CharField(blank=True, max_length=60)),
                ('form', models.CharField(blank=True, max_length=40)),
                ('frequency', models.CharField(blank=True, max_length=60)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
            ],
        ),
    ]
